name: edit_profile_rest
label: Edit Profile information

description: |
  This skillet demonstrates a simple REST api call to a PAN-OS NGFW to view the selected profile configuration

type: rest

extends:

labels:
  collection:
    - testing

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip_address
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password
 # - name: api_key
 #   description: API Key
 #   default: abc123
 #   type_hint: text
  - name: category
    description: url category
    default: adult
    type_hint: dropdown
    dd_list:
      - key: abortion
        value: abortion
      - key: adult
        value: adult
      - key: alcohol-and-tobacco
        value: alcohol-and-tobacco
      - key: copyright-infringement
        value: copyright-infringement
      - key: dating
        value: dating
      - key: extremism
        value: extremism
      - key: gambling
        value: gambling


snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    # this should output capturing which will set a variable called 'api_key' in the workflow, which can be referenced
    # in a skillet called after this one, any variable with a name called api_key will be prepopulated with the
    # value that is captured from the output of this xml api command
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key
  - name: profile_info
    path: https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/entry[@name='Outbound-URL']/alert/member[text()='{{ category }}']&key={{ api_key }}
    output_type: xml
    outputs:
      - name: profileName
        capture_pattern: result/{{ profile }}
  - name: profile_info
    path: https://{{ TARGET_IP }}/api/?type=config&action=set&xpath=/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/entry[@name='Outbound-URL']/block&element=<member>{{ category }}</member>&key={{ api_key }}
    output_type: xml
    outputs:
      - name: profileName
        capture_pattern: result/{{ profile }}
